version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "54401:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookstore
